### PR TITLE
Css canvas medical | Adrienne Yung

### PR DESCRIPTION
**Pull request by adrienne-yung**
css-canvas-medical2 pic

### CODE REVIEW

**Review by codingcodymiller — CHANGES_REQUESTED** [review]
Hey Adrienne! The color of the Contact Us button in the `nav` is incorrect as compared to the example, please revise

**Review by codingcodymiller — CHANGES_REQUESTED** [review]
Please provide an updated screenshot for visual changes 🙏 . You can message me on Slack when you have added the screenshot 👍

**Comment by adrienne-yung** [comment]
css-canvas-medical2 1 pic

**Review by codingcodymiller — CHANGES_REQUESTED** [review]
Hey Adrienne! A couple more notes around matching the example:
1. The "Ready to Learn More?" text is not indented as it is in the example
2. The "Ready to Learn More?" text also seems to be the wrong color
3. Your buttons have squared off edges, but in the example, they are slightly rounded

Please address these points, and make sure to submit a new screenshot with your revisions

**Comment by adrienne-yung** [comment]
css-canvas-medical2 2 pic

**Review by codingcodymiller — APPROVED** [review]
Great work!!

**Pull request merged**
